name = "worker"
main = "src/index.ts"
compatibility_date = "2022-10-16"
type = "javascript"
node_compat = true

kv_namespaces = [
]

[build]
command = "npm run build"

[build.upload]
format = "service-worker"